[package]
name = "myboxfs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
fuser = "0.18"
libc = "0.2"
rpassword = "7.4"
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "json",
    "multipart",
    "rustls-tls",
] }
serde = { version = "1", features = ["derive"] }
tracing = { version = "0.1", features = ["release_max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
